<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="MailKit" Version="4.12.1" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.0-preview.5.25277.114" />
    <PackageReference Include="MongoDB.Bson" Version="2.22.0" />
    <PackageReference Include="System.ServiceModel.Syndication" Version="9.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MeslekOdalari.DataAccess\MeslekOdalari.DataAccess.csproj" />
    <ProjectReference Include="..\MeslekOdalari.Entity\MeslekOdalari.Entity.csproj" />
  </ItemGroup>

</Project>
